title: Priya Harrys Blog
description: A Computer Science Journey
url: "https://yourusername.github.io"
baseurl: "" # Leave this empty unless you are serving from a subdirectory
theme: jekyll-theme-cayman # You can change this to
