title: My Blog
description: My awesome blog
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-cayman # default theme
