title: PH's Blog
description: A blog I am starting on my computer science journey
url: "https://captainsapphire.github.io"
baseurl: "" # leave empty unless you are serving from a subdirectory
theme: minima
